# Add locations to $PATH variable
HOMEBREW_PATH="/opt/homebrew/bin:/usr/local/bin"
VSCODE_PATH="/Application/Visual Studio Code.app/Contents/Resources/app/bin"

export PATH="$HOMEBREW_PATH:$PATH:$VSCODE_PATH:$PNPM_HOME"

# prep antidote
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh

# set omz variables
ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/oh-my-zsh"
[[ -d $ZSH_CACHE_DIR ]] || mkdir -p $ZSH_CACHE_DIR

zstyle ':antidote:bundle' use-friendly-names 'yes'
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 7

# Load all your secret environment variables from ~/.env and only files that end with .zsh
for file in "$HOME/.env/"*; do
    if [[ -f $file && $file == *.zsh ]]; then
        source "$file"
    fi
done

# load antidote
antidote load

# Syntax highligthing for man pages using bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# export NVM_DIR=~/.nvm
# source $(brew --prefix nvm)/nvm.sh

# Starship prompt
eval "$(starship init zsh)"

# Zoxide
eval "$(zoxide init zsh)"

source "$HOME/.shell/aliases.zsh"
source "$HOME/.shell/functions.zsh"

eval "$(fnm env --use-on-cd --shell zsh)"