import = [
    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 7
padding.y = 7

decorations = "Buttonless" 

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 14
